In [1]:
import pandas
from geopy.geocoders import Nominatim

In [5]:
locator = Nominatim(user_agent="myGeocoder")
location = locator.geocode("Champ de Mars, Paris, France")
print("Latitude = {}, Longitude = {}".format(location.latitude, location.longitude))

Latitude = 48.85614465, Longitude = 2.297820393322227

In [8]:
pandas.read_excel("sample.xlsx")

,ROWNUM,patient_name,patient_sex,patient_mobile,patient_age,patient_district_name,patient_address,patient_occupation,patient_designation,id_type_name,...,time_of_isolation_Id,time_of_outcome_name,time_of_outcome_Id,contact_patient_mobile,traceable_id,hi_Completion_status,hi_Completion_date,patient_active_status,icmr_Id,patient_Id
0,1,SURESH KUMAR,Male,9815450409,39,BATHINDA,bathinda,Other,NaN,SRF ID,...,0,NaN,0,NaN,1,N,NaN,Y,289276071.0,R008725
1,2,SANTOSH KUMAR,Male,9465251998,46,HOSHIARPUR,CITY DASUYA,Other,NaN,SRF ID,...,0,NaN,0,NaN,1,N,NaN,Y,284943521.0,nCoV-1633251
2,3,ANOOP,Male,9399630804,26,PATHANKOT,RO PATHANKOT,Other,NaN,SRF ID,...,0,NaN,0,NaN,1,N,NaN,Y,284702837.0,2019-nCoV163597
3,4,MUNISH,Male,9872216010,42,JALANDHAR,BHARGO CAMP,Other,NaN,SRF ID,...,0,NaN,0,NaN,1,N,NaN,Y,287965589.0,993203
4,5,TARLOCHAN SINGH,Male,9988993885,57,PATIALA,VILL. SHEKHPURA ENCLAVE,Other,NaN,SRF ID,...,0,NaN,0,NaN,1,N,NaN,Y,284787179.0,592380
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,995,RUTH SONIA TOPPO,Female,9356623300,27,LUDHIANA,CMC AND HOSPITAL,Other,NaN,SRF ID,...,0,NaN,0,NaN,1,N,NaN,Y,143157249.0,G92601
995,996,RITA RANI,Female,9877481748,48,S.A.S Nagar,3348 SECTOR 70 MOHALI,Other,NaN,SRF ID,...,0,NaN,0,NaN,1,N,NaN,Y,289423694.0,PBTI-nCov-17419
996,997,MEWA SINGH,Male,9878906357,67,SANGRUR,VILLAGE BANGA,Other,NaN,SRF ID,...,0,NaN,0,NaN,1,N,NaN,Y,289024483.0,ncov1611171
997,998,AMARJIT KAUR WALIA,Female,9815100614,72,JALANDHAR,HNO 614-R THE MALL MODEL TOWN,Other,NaN,SRF ID,...,0,NaN,0,NaN,1,N,NaN,Y,288383298.0,683686
998,999,BABLI,Female,7973953668,42,FAZILKA,DELHI PUBLIC SCHOOL,Other,NaN,SRF ID,...,0,NaN,0,NaN,1,N,NaN,Y,281628734.0,144701